//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryNoteFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNoteError
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Errors { get; set; }
        public string Warnings { get; set; }
    }
}
