//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryNoteFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliveryNoteEntities : DbContext
    {
        public DeliveryNoteEntities()
            : base("name=DeliveryNoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeliveryNoteError> DeliveryNoteErrors { get; set; }
        public virtual DbSet<DelNote> DelNotes { get; set; }
        public virtual DbSet<DelNoteItem> DelNoteItems { get; set; }
    }
}
