//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryNoteFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelNote
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public string CustomerIDF { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<decimal> PaymentSum { get; set; }
        public Nullable<decimal> TotalDiscounts { get; set; }
        public string CreditNoteType { get; set; }
        public string CreditNoteDescr { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<byte> PaymentTimeID { get; set; }
        public Nullable<System.DateTime> PaymentConsignDate { get; set; }
        public Nullable<bool> isNZOK { get; set; }
        public Nullable<bool> isRebateDiscount { get; set; }
        public string KSCOrderNo { get; set; }
    }
}
